name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  flutter_animate: ^4.5.2
  introduction_screen: ^4.0.0
  json_annotation: ^4.9.0
  dio: ^5.4.3+1                # Para requisições de API
  flutter_secure_storage: ^9.2.2  # Para salvar o token
  getwidget: ^3.1.1
  geolocator: ^10.0.0
  geocoding: ^2.0.5
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.8.0
  json_serializable: ^6.11.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/banners/
    - assets/others/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: AirbnbCereal
      fonts:
        - asset: assets/fonts/AirbnbCereal_W_Lt.otf
          weight: 300
        - asset: assets/fonts/AirbnbCereal_W_Bk.otf
          weight: 400
        - asset: assets/fonts/AirbnbCereal_W_Md.otf
          weight: 500
        - asset: assets/fonts/AirbnbCereal_W_Bd.otf
          weight: 700
        - asset: assets/fonts/AirbnbCereal_W_XBd.otf
          weight: 800
        - asset: assets/fonts/AirbnbCereal_W_Blk.otf
          weight: 900

# CORREÇÃO APLICADA AQUI:
# Esta seção está agora no nível raiz do arquivo, sem indentação.
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21